spring:
  application:
    name: agp-protocol
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/agp_protocol?createDatabaseIfNotExist=true
    username: root
    password:
